### PR TITLE
Release 2.1.0

### PR DESCRIPTION
**Pull request by RhinosF1**
Changes:
- Improvements to CI
- Compatibility: ensure with latest version of MirahezeBot-Plugins, bump sopel-help check to latest version
- Developers: Update setuptools, build, flake8-simplify, pip-check-reqs, flake8-docstrings, flake8-comprehensions, flake8-pytest-style
- Ensure code is more efficient
- Use generic examples for help
- Update email for package

### CODE REVIEW

**Comment by RhinosF1** [comment]
I can deploy this tonight.

@dmehus: do you want to prep the text of the blog post?

**Review by MacFan4000 — DISMISSED** [review]
LGTM but the build is broken

**Review by sario528 — APPROVED** [review]
LGTM, and all checks are now passing

**Comment by RhinosF1** [comment]
Just waiting on @dmehus to give me a blog

**Review by MacFan4000 — APPROVED** [review]

**Pull request merged**
